# Generated by Django 4.2.9 on 2024-01-19 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                (
                    "difficulty",
                    models.CharField(choices=[("E", "Easy"), ("M", "Medium"), ("H", "Hard")], max_length=1),
                ),
                ("questions_qt", models.PositiveIntegerField(default=1)),
                ("categories", models.ManyToManyField(to="flashcards.category")),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeFlashcard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_correct", models.BooleanField(default=False)),
                ("is_answered", models.BooleanField(default=False)),
                (
                    "challenge",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="challenges.challenge"),
                ),
                (
                    "flashcard",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="flashcards.flashcard"),
                ),
            ],
            options={
                "verbose_name": "Challenge Flashcard",
                "verbose_name_plural": "Challenge Flashcards",
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="flashcards",
            field=models.ManyToManyField(through="challenges.ChallengeFlashcard", to="flashcards.flashcard"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="challengeflashcard",
            constraint=models.UniqueConstraint(fields=("challenge", "flashcard"), name="unique_challenge_flashcard"),
        ),
        migrations.AlterUniqueTogether(
            name="challengeflashcard",
            unique_together={("challenge", "flashcard")},
        ),
    ]
